spring:
  datasource:
    db_0:
      url: jdbc:mysql://localhost:3306/db_0
      username: root
      password:
    db_1:
      url: jdbc:mysql://localhost:3306/db_1
      username: root
      password: